INSERT INTO torque_specs (model_id, category_id, description, n_m, ft_lbs, in_lbs, comments)
VALUES
-- ABS
(2,1,'Antilock brake system (ABS) module bolt',8,null,70,null),
(2,1,'Front wheel speed sensors bolt',7,5,62,null),
(2,1,'Front brake lines at hydraulic control unit',23,17,null,null),
(2,1,'Hydraulic control unit (HCU) bracket bolts',9,7,80,null),
(2,1,'Primary brake lines to hydraulic control unit',25,18,null,null),
(2,1,'Rear wheel speed sensors bolt',11,8,97,null),
(2,1,'Rear brake lines to hydraulic control unit',23,17,null,null),
(2,1,'Secondary brake lines to hydraulic control unit',23,17,null,null),
-- Body
(2,2,'A-pillar grab handle bolts',9,null,80,null);
(2,'B-Pillar grab handle bolts',9,null,80,null),
(2,'Backlite to hard top bolts',11,8,null,null),
(2,'Body isolator front - body nuts',48,35,null,null),
(2,'Body isolator front - frame nut',66,49,null,'Turn an additional 155°'),
(2,'Body isolator A-pillar bolt',125,92,null,null),
(2,'Body isolator B-pillar bolt - body bolt',125,92,null,null);
(2,'Body isolator B-pillar bolt - frame nuts',null,null,null,null),
(2,'Body isolator C-pillar bolt - body bolt',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
(2,'',null,null,null,null),
