INSERT INTO torque_specs (id, category_id, description, n_m, ft_lbs, in_lbs, comments)
VALUES 
(9,2,'A-pillar grab handle bolts',9,null,80,null),
(10,2,'B-Pillar grab handle bolts',9,null,80,null),
(11,2,'Backlite to hard top bolts',11,8,null,null),
(12,2,'Body isolator front - body nuts',48,35,null,null),
(13,2,'Body isolator front - frame nut',66,49,null,'Turn an additional 155°'),
(14,2,'Body isolator A-pillar bolt',125,92,null,null),
(15,2,'Body isolator B-pillar bolt - body bolt',125,92,null,null);
(16,2,'Body isolator B-pillar bolt - frame nuts',null,null,null,null),
(17,2,'Body isolator C-pillar bolt - body bolt',null,null,null,null),
(18,2,'',null,null,null,null),
(19,2,'',null,null,null,null),
(20,2,'',null,null,null,null),
(21,2,'',null,null,null,null),
(22,2,'',null,null,null,null),
(23,2,'',null,null,null,null),
(24,2,'',null,null,null,null),
(25,2,'',null,null,null,null),
(26,2,'',null,null,null,null),
(27,2,'',null,null,null,null),
(28,2,'',null,null,null,null),
(29,2,'',null,null,null,null),
(30,2,'',null,null,null,null),
(31,2,'',null,null,null,null),
(32,2,'',null,null,null,null),
(33,2,'',null,null,null,null),
(34,2,'',null,null,null,null),
(35,2,'',null,null,null,null),
